# Generated by Django 4.2.5 on 2023-10-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
               
                ('time', models.CharField(max_length=100)),
                ('pLength', models.CharField(max_length=100)),
                ('dstIp', models.CharField(max_length=100)),
                ('srcIP', models.CharField(max_length=100)),
                ('dstPort', models.CharField(max_length=100)),
                ('srcPort', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empid', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('Department', models.CharField(max_length=25)),
            ],
        ),
    ]
