# Generated by Django 4.2.5 on 2023-10-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=100)),
                ('severity_level', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('ip_src', models.CharField(max_length=100)),
                ('port_src', models.CharField(max_length=100)),
                ('ip_dst', models.CharField(max_length=100)),
                ('port_dst', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=100)),
                ('descripton', models.CharField(max_length=500)),
                ('info', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empid', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('Department', models.CharField(max_length=25)),
            ],
        ),
    ]
